spring.application.name=banking-api

spring.datasource.url=jdbc:postgresql://localhost:5432/banking_db
spring.datasource.username=postgres
spring.datasource.password=banking@2026

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true